apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 'banking-gateway'
  namespace: banking
  description: 'Catalogo temporário de testes do banking api gateway'
  tags:
    - banking-integrar-bis-devs
    - banking
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: backend
  lifecycle: experimental
  owner: stone-payments/banking-integrar